---
language: minimal
services: docker

before_install:
  - sudo apt-get -y -o Dpkg::Options::="--force-confnew" install docker-ce

addons:
  apt:
    update: true

cache:
  directories:
    - $HOME/.cache/pre-commit

env:
  matrix:
    - BASE_IMAGE: debian:10
    - BASE_IMAGE: debian:sid
    - BASE_IMAGE: ubuntu:18.04
    - BASE_IMAGE: ubuntu:20.04

jobs:
  include:
    - name: lint with pre-commit
      language: python
      install: skip
      script:
        - pip3 install pre-commit
        - pre-commit run -c .travis-pre-commit-config.yaml -a

script:
  - docker build . -t fauust/docker-systemd:${BASE_IMAGE/:/-} --build-arg base_image=$BASE_IMAGE
  - docker run --rm -it -v /var/run/docker.sock:/var/run/docker.sock -v $(pwd):/mnt -w /mnt wagoodman/dive:latest --ci fauust/docker-systemd:${BASE_IMAGE/:/-}
  - docker run --name test-${BASE_IMAGE/:/-} -d --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro fauust/docker-systemd:${BASE_IMAGE/:/-}
  - sleep 2
  - docker exec -t test-${BASE_IMAGE/:/-} systemd-analyze
