#!/usr/bin/env bash

set -o nounset
set -o pipefail
set -o posix

typeset TAG="fauust/docker-systemd:${BASE_IMAGE/:/-}"
podman build . --no-cache -t "${TAG/-slim/}" --build-arg base_image="$BASE_IMAGE"
