#!/usr/bin/env bash
#
# See:
# https://docs.docker.com/docker-hub/builds/advanced/

set -o nounset
set -o pipefail
set -o posix

# get tags to build from .travis.yml file
grep -E "(debian|ubuntu):" <.github/workflows/build.yml |
  grep -v BASE_IMAGE |
  cut -d '"' -f2 |
  while IFS= read -r BASE_IMAGE; do
    TAG="fauust/docker-systemd:${BASE_IMAGE/:/-}"
    docker build . --no-cache -t "${TAG/-slim/}" --build-arg base_image="$BASE_IMAGE"
  done
