#!/usr/bin/env bash

set -o nounset
set -o pipefail
set -o posix

typeset TAG="fauust/docker-systemd:${BASE_IMAGE/:/-}"
podman build . --no-cache -t "${TAG/-slim/}" --build-arg base_image="$BASE_IMAGE"
podman run --name "test-container" -d "${TAG/-slim/}"
sleep 2
podman exec "test-container" systemd-analyze
podman stop --name "test-container"
