#!/usr/bin/env bash
#
# See:
# https://docs.docker.com/docker-hub/builds/advanced/

set -o nounset
set -o pipefail
set -o posix

# only push if on master branch
if [[ $SOURCE_BRANCH == "master" ]]; then
  for tag in $(docker images fauust/docker-systemd --format "{{.Tag}}"); do
    docker push "fauust/docker-systemd:${tag}"
  done
fi
